kumuluzee:
  name: products
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/ProductsDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/product
      username: dbuser
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379